name: Nightly Cypress Tests

on:
  schedule:
    # 10:00 AM Barcelona time (CEST/UTC+2 currently)
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      TERM: xterm   # Prevents "tput: No value for $TERM" warnings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: |
          echo "::group::Running Cypress tests"
          npx cypress run || { 
            echo "::error::❌ Cypress tests failed. Check screenshots artifact."; 
            exit 1; 
          }
          echo "::endgroup::"

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots